"use client";
import {useState,useMemo} from 'react';
import type {Exercise,WorkoutHistoryEntry,WorkoutSet,MuscleGroup} from './types';
import {AnatomyMap,ExerciseArt,hasExerciseArt} from './TrainingVisuals';
type Units='metric'|'imperial';
const dayKey=(d:string|Date)=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const valid=(s:WorkoutSet)=>s.completed&&s.reps>0&&Number.isFinite(s.weight)&&s.weight>=0;
const working=(s:WorkoutSet)=>{if(!valid(s))return false;try{return JSON.parse(localStorage.getItem('bodypilot-set-types')||'{}')[s.id]!=='W'}catch{return true}};
const sets=(w:WorkoutHistoryEntry)=>w.exercises.flatMap(e=>e.sets).filter(valid);
const volume=(w:WorkoutHistoryEntry)=>sets(w).reduce((a,s)=>a+s.weight*s.reps,0);
const estimate=(s:WorkoutSet)=>s.weight>0&&s.reps>0&&s.reps<=12?s.weight*(s.reps===1?1:1+s.reps/30):0;
const weight=(v:number,u:Units)=>`${(v*(u==='imperial'?2.2046226218:1)).toLocaleString(undefined,{maximumFractionDigits:1})} ${u==='imperial'?'lb':'kg'}`;
const date=(v:string)=>new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric'});
const sorted=(h:WorkoutHistoryEntry[])=>[...h].filter(w=>Number.isFinite(Date.parse(w.finishedAt))).sort((a,b)=>Date.parse(a.finishedAt)-Date.parse(b.finishedAt));
function Card({title,children,extra,className=""}:{title:string;children:React.ReactNode;extra?:React.ReactNode;className?:string}){return <section className={`mv-card ${className}`}><div className="mv-card-heading"><h3>{title}</h3>{extra}</div>{children}</section>}
function Empty({children}:{children:React.ReactNode}){return <p className="mv-empty">{children}</p>}
function Range({value,onChange}:{value:number;onChange:(v:number)=>void}){return <div className="mv-segments">{[7,30,90,365,0].map(v=><button key={v} className={v===value?'active':''} onClick={()=>onChange(v)}>{({7:'1W',30:'1M',90:'3M',365:'1Y',0:'All'} as Record<number,string>)[v]}</button>)}</div>}
function inRange(h:WorkoutHistoryEntry[],days:number){const end=Date.now();return sorted(h).filter(w=>Date.parse(w.finishedAt)<=end&&(!days||Date.parse(w.finishedAt)>=end-days*864e5))}
function Curve({series,unit}:{series:Array<{name:string;points:Array<{t:number;v:number}>}>;unit:string}){
 const points=series.flatMap(s=>s.points);if(!points.length)return <Empty>Complete sets to build your strength trend.</Empty>;
 const minT=Math.min(...points.map(p=>p.t)),maxT=Math.max(...points.map(p=>p.t));const maxV=Math.max(1,...points.map(p=>p.v))*1.1;
 const colors=['#009b48','#67ae83','#164d32'];const x=(t:number)=>42+((t-minT)/(maxT-minT||1))*300,y=(v:number)=>156-v/maxV*130;
 return <><svg className="mv-chart" viewBox="0 0 360 190" role="img" aria-label={`Estimated strength trend in ${unit}`}>
 {[0,.5,1].map(v=><g key={v}><line x1="42" x2="344" y1={y(v*maxV)} y2={y(v*maxV)} stroke="#edf0ee"/><text x="34" y={y(v*maxV)+3} textAnchor="end">{Math.round(v*maxV)}</text></g>)}
 {series.map((s,i)=><g key={s.name}><polyline fill="none" stroke={colors[i%3]} strokeWidth="2.5" points={s.points.map(p=>`${x(p.t)},${y(p.v)}`).join(' ')}/>{s.points.map((p,j)=><circle key={j} cx={x(p.t)} cy={y(p.v)} r="3" fill={colors[i%3]}><title>{new Date(p.t).toLocaleDateString()} · {p.v.toFixed(1)} {unit}</title></circle>)}</g>)}
 <text x="42" y="181">{new Date(minT).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</text><text x="344" y="181" textAnchor="end">{new Date(maxT).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</text></svg><div className="mv-legend">{series.map((s,i)=><span key={s.name}><i style={{background:colors[i%3]}}/>{s.name}</span>)}</div></>;
}
function Bars({items,units}:{items:Array<{label:string;v:number}>;units:Units}){const max=Math.max(1,...items.map(x=>x.v));return <div className="mv-bars">{items.map((x,i)=><div key={i}><div title={`${x.label}: ${weight(x.v,units)}`} style={{height:`${x.v?Math.max(2,x.v/max*105):0}px`}}/><span>{i===0||i===items.length-1||i%3===0?x.label:''}</span></div>)}</div>}
function exerciseSeries(history:WorkoutHistoryEntry[],id:string){return sorted(history).flatMap(w=>{const ss=w.exercises.filter(e=>e.exerciseId===id).flatMap(e=>e.sets).filter(valid);const best=Math.max(0,...ss.map(estimate));return best?[{t:Date.parse(w.finishedAt),v:best}]:[]})}
export function ProgressView({history,exercises,displayUnits}:{history:WorkoutHistoryEntry[];exercises:Exercise[];displayUnits:Units}){
 const [range,setRange]=useState(90),[selected,setSelected]=useState(''),[muscle,setMuscle]=useState<MuscleGroup|undefined>(),[expandedTargets,setExpandedTargets]=useState(false);
 const [targets,setTargets]=useState<Record<string,number>>(()=>{try{return JSON.parse(localStorage.getItem('mucipes-muscle-targets')||'{}')}catch{return {}}});
 const recent=inRange(history,range),factor=displayUnits==='imperial'?2.2046226218:1;
 const ids=Array.from(new Map(recent.flatMap(w=>w.exercises).map(e=>[e.exerciseId,e.exerciseName])).entries());
 const top=ids.map(([id,name])=>({id,name,points:exerciseSeries(recent,id).map(p=>({...p,v:p.v*factor}))})).filter(s=>s.points.length).sort((a,b)=>b.points.length-a.points.length).slice(0,3);
 const counts:Partial<Record<MuscleGroup,number>>={};recent.forEach(w=>w.exercises.forEach(e=>{const g=exercises.find(x=>x.id===e.exerciseId)?.muscleGroup||'Other';counts[g]=(counts[g]||0)+e.sets.filter(working).length}));
 const monday=new Date();monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-(monday.getDay()+6)%7);
 const weekly:Record<string,number>={};history.filter(w=>Date.parse(w.finishedAt)>=+monday&&Date.parse(w.finishedAt)<=Date.now()).forEach(w=>w.exercises.forEach(e=>{const g=exercises.find(x=>x.id===e.exerciseId)?.muscleGroup||'Other';weekly[g]=(weekly[g]||0)+e.sets.filter(working).length}));
 const groups=['Chest','Back','Shoulders','Biceps','Triceps','Quads','Hamstrings','Glutes','Calves','Abs'];
 const end=Date.now(),start=range?end-range*864e5:Math.min(end-864e5,...recent.map(w=>Date.parse(w.finishedAt)));const bins=12,step=(end-start)/bins;
 const buckets=Array.from({length:bins},(_,i)=>{const from=start+i*step,to=i===bins-1?end+1:from+step;return {label:date(new Date(from).toISOString()),v:recent.filter(w=>Date.parse(w.finishedAt)>=from&&Date.parse(w.finishedAt)<to).reduce((a,w)=>a+volume(w),0)}});
 const chosen=selected||ids[0]?.[0]||'';
 const [metric,setMetric]=useState<'strength'|'volume'>('strength');
 const one=metric==='strength'?exerciseSeries(recent,chosen):recent.flatMap(w=>{const es=w.exercises.filter(e=>e.exerciseId===chosen);return es.length?[{t:Date.parse(w.finishedAt),v:es.flatMap(e=>e.sets).filter(valid).reduce((s,x)=>s+x.weight*x.reps,0)}]:[]});
 return <div className="mv-view mv-progress"><header className="mv-title"><h2>Progress</h2><Range value={range} onChange={setRange}/></header>
 <div className="mv-stat-grid"><div><span>Total volume</span><strong>{weight(recent.reduce((n,w)=>n+volume(w),0),displayUnits)}</strong></div><div><span>Workouts</span><strong>{recent.length}</strong></div><div><span>Avg. duration</span><strong>{recent.length?Math.round(recent.reduce((n,w)=>n+w.durationSeconds,0)/recent.length/60):0} min</strong></div></div>
 <div className="mv-trends"><Card title="Volume trend"><Bars items={buckets} units={displayUnits}/></Card><Card title="Strength · e1RM"><Curve series={top} unit={displayUnits==='imperial'?'lb':'kg'}/></Card></div>
 <div className="mv-target-map"><Card title="Weekly set targets" extra={<span className="mv-muted">Since Monday</span>}><div className="mv-target-grid">{(expandedTargets?groups:['Chest','Back','Shoulders','Quads','Hamstrings']).map(g=><div className="mv-target" key={g}><div><span>{g}</span><label>{weekly[g]||0} / <input aria-label={`${g} weekly target`} type="number" min="0" max="100" placeholder="—" value={targets[g]??''} onChange={e=>{const next={...targets};if(e.target.value==='')delete next[g];else next[g]=Math.max(0,Math.min(100,Number(e.target.value)));setTargets(next);localStorage.setItem('mucipes-muscle-targets',JSON.stringify(next))}}/></label></div><div className="mv-track"><i style={{width:`${targets[g]?Math.min(100,(weekly[g]||0)/targets[g]*100):0}%`}}/></div></div>)}</div><button className="mv-link mv-target-toggle" onClick={()=>setExpandedTargets(!expandedTargets)}>{expandedTargets?'Show fewer muscles':'All muscle targets ›'}</button><p className="mv-footnote">Enter your weekly goals. Warm-ups excluded.</p></Card><Card title="Muscle map"><AnatomyMap counts={counts} selected={muscle} onSelect={setMuscle}/><p className="mv-footnote">Primary muscle · completed sets in selected period.</p></Card></div>
 <details className="mv-more-progress"><summary>Explore individual exercise progress</summary><Card title="Exercise progress"><select className="mv-select" value={chosen} onChange={e=>setSelected(e.target.value)}>{ids.length?ids.map(([id,n])=><option value={id} key={id}>{n}</option>):<option>No exercises logged</option>}</select><div className="mv-segments"><button onClick={()=>setMetric('strength')} className={metric==='strength'?'active':''}>e1RM</button><button onClick={()=>setMetric('volume')} className={metric==='volume'?'active':''}>Workload</button></div><Curve series={[{name:metric==='strength'?'Estimated 1RM':'Session volume',points:one.map(p=>({...p,v:p.v*factor}))}]} unit={displayUnits==='imperial'?'lb':'kg'}/><p className="mv-footnote">e1RM uses completed weighted sets of 1–12 reps. Workload is recorded weight × reps.</p></Card></details></div>;
}
export function HistoryView({history,deleteHistoryEntry,displayUnits}:{history:WorkoutHistoryEntry[];deleteHistoryEntry:(id:string)=>void;displayUnits:Units}){
 const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[selected,setSelected]=useState(''),[open,setOpen]=useState(''),[query,setQuery]=useState('');
 const all=sorted(history).reverse();const monthKey=dayKey(month).slice(0,7);const shown=all.filter(w=>dayKey(w.finishedAt).startsWith(monthKey)&&(!selected||dayKey(w.finishedAt)===selected)&&`${w.name} ${w.exercises.map(e=>e.exerciseName).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 const days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(),offset=(month.getDay()+6)%7;
 const change=(n:number)=>{setMonth(new Date(month.getFullYear(),month.getMonth()+n,1));setSelected('')};
 return <div className="mv-view mv-history"><header className="mv-title"><h2>History</h2><span className="mv-muted">{history.length} sessions</span></header><Card title={month.toLocaleDateString(undefined,{month:'long',year:'numeric'})} extra={<div><button aria-label="Previous month" className="mv-circle" onClick={()=>change(-1)}>‹</button><button aria-label="Next month" className="mv-circle" onClick={()=>change(1)}>›</button></div>}><div className="mv-calendar">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><span key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><i key={`pad${i}`}/>)}{Array.from({length:days},(_,i)=>{const key=dayKey(new Date(month.getFullYear(),month.getMonth(),i+1)),has=all.some(w=>dayKey(w.finishedAt)===key);return <button key={key} className={selected===key?'selected':''} onClick={()=>setSelected(selected===key?'':key)}>{i+1}{has&&<i/>}</button>})}</div>{selected&&<button className="mv-link" onClick={()=>setSelected('')}>Show whole month</button>}</Card><input className="mv-search" placeholder="Search sessions or exercises" value={query} onChange={e=>setQuery(e.target.value)}/><h3 className="mv-section-label">Completed sessions</h3>
 {!shown.length&&<Empty>No sessions in this selection. Choose another month or finish a workout.</Empty>}
 {shown.map(w=>{const older=all.filter(x=>Date.parse(x.finishedAt)<Date.parse(w.finishedAt));const previous=older.find(x=>x.name.trim().toLowerCase()===w.name.trim().toLowerCase());const pr=w.exercises.filter(e=>{const before=exerciseSeries(older,e.exerciseId);const now=Math.max(0,...e.sets.filter(valid).map(estimate));return before.length>0&&now>Math.max(...before.map(p=>p.v))}).length;return <Card className="mv-session" key={w.id} title={w.name} extra={<button className="mv-link" onClick={()=>setOpen(open===w.id?'':w.id)}>{open===w.id?'Close':'Details ›'}</button>}><div className="mv-session-date">{new Date(w.finishedAt).toLocaleDateString(undefined,{weekday:'short',day:'numeric',month:'short'})} · {Math.round(w.durationSeconds/60)} min {pr>0&&<span className="mv-pr">★ {pr} PR{pr===1?'':'s'}</span>}</div><div className="mv-session-stats"><span>{sets(w).length} sets</span><span>{weight(volume(w),displayUnits)}</span><span>{w.exercises.length} exercises</span></div>{open===w.id&&<div className="mv-session-detail">{previous&&<p className="mv-footnote">Previous {w.name}: {weight(volume(previous),displayUnits)} · {date(previous.finishedAt)}{volume(previous)>0?` · volume ${((volume(w)/volume(previous)-1)*100).toFixed(1)}%`:''}</p>}{w.exercises.map(e=><div key={e.id}><h4>{e.exerciseName}</h4>{e.sets.filter(valid).map((s,i)=><p key={s.id}>{i+1} <strong>{weight(s.weight,displayUnits)} × {s.reps}</strong><span>{s.rir!==null?`${s.rir} RIR`:''}</span></p>)}</div>)}<button className="mv-delete" onClick={()=>deleteHistoryEntry(w.id)}>Delete session</button></div>}</Card>})}</div>;
}
export function ExerciseView({exercises,history,displayUnits,addCustomExercise,deleteCustomExercise,onAdd}:{exercises:Exercise[];history:WorkoutHistoryEntry[];displayUnits:Units;addCustomExercise:(e:Exercise)=>void;deleteCustomExercise:(id:string)=>void;onAdd:(e:Exercise)=>void}){
 const [search,setSearch]=useState(''),[group,setGroup]=useState('All'),[chosen,setChosen]=useState<Exercise|null>(null),[range,setRange]=useState(90),[onlyFavorites,setOnlyFavorites]=useState(false),[limit,setLimit]=useState(24),[allHistory,setAllHistory]=useState(false);
 const [favorites,setFavorites]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem('bodypilot-exercise-favorites')||'[]')}catch{return []}});
 const fav=(id:string)=>{const next=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];setFavorites(next);localStorage.setItem('bodypilot-exercise-favorites',JSON.stringify(next))};
 const groups=['Chest','Back','Shoulders','Biceps','Triceps','Quads','Hamstrings','Glutes','Calves','Abs'];
 const filtered=exercises.filter(e=>(group==='All'||e.muscleGroup===group)&&e.name.toLowerCase().includes(search.toLowerCase())&&(!onlyFavorites||favorites.includes(e.id))).sort((a,b)=>Number(hasExerciseArt(b.name))-Number(hasExerciseArt(a.name))||a.name.localeCompare(b.name));
 const sessions=chosen?inRange(history,range).filter(w=>w.exercises.some(e=>e.exerciseId===chosen.id)).reverse():[];
 return <div className="mv-view mv-exercises"><header className="mv-title"><h2>Exercises</h2><select className="mv-group-select" aria-label="Muscle group" value={group} onChange={e=>{setGroup(e.target.value);setChosen(null);setLimit(24)}}>{['All',...groups,'Other'].map(g=><option key={g} value={g}>{g==='All'?'All muscles':g}</option>)}</select></header>
 <input className="mv-search" value={search} onChange={e=>{setSearch(e.target.value);setChosen(null);setLimit(24)}} placeholder="Search exercises…"/>
 <div className="mv-muscle-filters">{groups.map(g=><button key={g} className={group===g?'active':''} onClick={()=>{setGroup(group===g?'All':g);setChosen(null);setLimit(24)}}><AnatomyMap counts={{[g]:1}}/><span>{g}</span></button>)}</div>
 {chosen?<><button className="mv-link mv-back" onClick={()=>setChosen(null)}>‹ Exercise library</button><section className="mv-card mv-exercise-summary"><ExerciseArt name={chosen.name}/><div><div className="mv-card-heading"><h3>{chosen.name}</h3><button aria-label="Toggle favorite" className="mv-link" onClick={()=>fav(chosen.id)}>{favorites.includes(chosen.id)?'★':'☆'}</button></div><span className="mv-badge">{chosen.muscleGroup}</span><button className="mv-add-exercise" onClick={()=>onAdd(chosen)}>＋ Add to workout</button></div></section>
 <Card title="Strength progress (e1RM)" extra={<Range value={range} onChange={setRange}/>}><Curve series={[{name:chosen.name,points:exerciseSeries(sessions,chosen.id).map(p=>({...p,v:p.v*(displayUnits==='imperial'?2.2046226218:1)}))}]} unit={displayUnits==='imperial'?'lb':'kg'}/></Card>
 <Card title="Recent history · best set" extra={sessions.length>4?<button className="mv-link" onClick={()=>setAllHistory(!allHistory)}>{allHistory?'Show less':'View all'}</button>:undefined}>{sessions.length?(allHistory?sessions:sessions.slice(0,4)).map(w=><div className="mv-history-row" key={w.id}><span>{date(w.finishedAt)}</span><strong>{w.exercises.filter(e=>e.exerciseId===chosen.id).flatMap(e=>e.sets).filter(valid).sort((a,b)=>estimate(b)-estimate(a)||b.weight-a.weight||b.reps-a.reps).slice(0,1).map(s=>`${weight(s.weight,displayUnits)} × ${s.reps}${s.rir!==null?` · ${s.rir} RIR`:''}`).join(' / ')}</strong></div>):<Empty>No completed sets yet.</Empty>}</Card>{chosen.custom&&<button className="mv-delete" onClick={()=>{if(window.confirm('Delete this custom exercise? Existing history stays saved.')){deleteCustomExercise(chosen.id);setChosen(null)}}}>Delete custom exercise</button>}</>:<>
 <div className="mv-card-heading"><span className="mv-muted">{filtered.length} exercises</span><button className="mv-link" onClick={()=>setOnlyFavorites(!onlyFavorites)}>{onlyFavorites?'★ Favorites':'☆ Favorites'}</button><button className="mv-link" onClick={()=>{const name=window.prompt('New exercise name');if(!name?.trim())return;if(exercises.some(e=>e.name.toLowerCase()===name.trim().toLowerCase())){window.alert('This exercise already exists.');return}addCustomExercise({id:`custom-${Date.now()}`,name:name.trim(),muscleGroup:(group==='All'?'Other':group) as MuscleGroup,custom:true})}}>+ Create</button></div>
 <div className="mv-library">{filtered.slice(0,limit).map(e=><button key={e.id} className="mv-library-card" onClick={()=>{setChosen(e);setGroup(e.muscleGroup);setAllHistory(false)}}><ExerciseArt name={e.name} compact/><div><strong>{e.name}</strong><span>{e.muscleGroup}{favorites.includes(e.id)?' · ★':''}</span></div><b>›</b></button>)}</div>{filtered.length>limit&&<button className="mv-primary secondary" onClick={()=>setLimit(limit+24)}>Show more exercises</button>}{!filtered.length&&<Empty>No matching exercises.</Empty>}</>}
 </div>;
}
