import type { Exercise } from "./types";

// BodyPilot exercise library generated from the RepDB Free dataset.
// Attribution required by source dataset: Exercise data by RepDB (repdb.co).
// Total exercises: 601

export const defaultExercises: Exercise[] = [
  { id: "ab-wheel-rollout", name: "Ab Wheel Rollout", muscleGroup: "Abs" },
  { id: "air-bike", name: "Air Bike", muscleGroup: "Other" },
  { id: "archer-pull-ups", name: "Archer Pull Ups", muscleGroup: "Back" },
  { id: "archer-push-ups", name: "Archer Push Ups", muscleGroup: "Chest" },
  { id: "arnold-press", name: "Arnold Press", muscleGroup: "Shoulders" },
  { id: "assisted-dips", name: "Machine Assisted Dips", muscleGroup: "Triceps" },
  { id: "assisted-pull-ups", name: "Assisted Pull Ups", muscleGroup: "Back" },
  { id: "back-extension", name: "Back Extension", muscleGroup: "Back" },
  { id: "back-lever", name: "Back Lever", muscleGroup: "Other" },
  { id: "ball-leg-curl", name: "Stability Ball Leg Curl", muscleGroup: "Hamstrings" },
  { id: "ball-pike", name: "Ball Pike", muscleGroup: "Abs" },
  { id: "band-assisted-pull-ups", name: "Band Assisted Pull Ups", muscleGroup: "Back" },
  { id: "band-pull-apart", name: "Band Pull Apart", muscleGroup: "Shoulders" },
  { id: "banded-adductor-stretch", name: "Banded Adductor Stretch", muscleGroup: "Other" },
  { id: "banded-ankle-stretch", name: "Banded Ankle Stretch", muscleGroup: "Calves" },
  { id: "banded-calf-stretch", name: "Banded Calf Stretch", muscleGroup: "Calves" },
  { id: "banded-chest-stretch", name: "Banded Chest Stretch", muscleGroup: "Chest" },
  { id: "banded-clamshell", name: "Banded Clamshell", muscleGroup: "Glutes" },
  { id: "banded-figure-4-stretch", name: "Banded Figure-4 Stretch", muscleGroup: "Glutes" },
  { id: "banded-fire-hydrant", name: "Banded Fire Hydrant", muscleGroup: "Glutes" },
  { id: "banded-glute-bridge", name: "Banded Glute Bridge", muscleGroup: "Glutes" },
  { id: "banded-good-morning", name: "Banded Good Morning", muscleGroup: "Hamstrings" },
  { id: "banded-hamstring-stretch", name: "Banded Hamstring Stretch", muscleGroup: "Hamstrings" },
  { id: "banded-hip-thrust", name: "Banded Hip Thrust", muscleGroup: "Glutes" },
  { id: "banded-it-band-stretch", name: "Banded IT-Band Stretch", muscleGroup: "Other" },
  { id: "banded-kneeling-hip-thrust", name: "Banded Kneeling Hip Thrust", muscleGroup: "Glutes" },
  { id: "banded-lat-stretch", name: "Banded Lat Stretch", muscleGroup: "Back" },
  { id: "banded-lateral-walk", name: "Banded Lateral Walk", muscleGroup: "Glutes" },
  { id: "banded-rear-delt-stretch", name: "Banded Rear Delt Stretch", muscleGroup: "Shoulders" },
  { id: "banded-romanian-deadlift", name: "Banded Romanian Deadlift", muscleGroup: "Hamstrings" },
  { id: "banded-seated-hip-abduction", name: "Banded Seated Hip Abduction", muscleGroup: "Glutes" },
  { id: "banded-shoulder-stretch", name: "Banded Shoulder Stretch", muscleGroup: "Shoulders" },
  { id: "banded-squat", name: "Banded Squat", muscleGroup: "Glutes" },
  { id: "banded-standing-curl", name: "Banded Standing Leg Curl", muscleGroup: "Hamstrings" },
  { id: "banded-standing-hip-abduction", name: "Banded Standing Hip Abduction", muscleGroup: "Glutes" },
  { id: "banded-standing-hip-adduction", name: "Banded Standing Hip Adduction", muscleGroup: "Other" },
  { id: "banded-sumo-walk", name: "Banded Sumo Walk", muscleGroup: "Glutes" },
  { id: "banded-terminal-knee-extension", name: "Banded Terminal Knee Extension", muscleGroup: "Quads" },
  { id: "banded-triceps-stretch", name: "Banded Triceps Stretch", muscleGroup: "Triceps" },
  { id: "barbell-ab-rollout", name: "Barbell Ab Rollout", muscleGroup: "Abs" },
  { id: "barbell-calf-raise", name: "Barbell Calf Raise", muscleGroup: "Calves" },
  { id: "barbell-curl", name: "Barbell Curl", muscleGroup: "Biceps" },
  { id: "barbell-front-raise", name: "Barbell Front Raise", muscleGroup: "Shoulders" },
  { id: "barbell-glute-bridge", name: "Barbell Glute Bridge", muscleGroup: "Glutes" },
  { id: "barbell-lunge", name: "Barbell Lunge", muscleGroup: "Glutes" },
  { id: "barbell-overhead-extension", name: "Barbell Overhead Extension", muscleGroup: "Triceps" },
  { id: "barbell-preacher-curl", name: "Barbell Preacher Curl", muscleGroup: "Biceps" },
  { id: "barbell-pullover", name: "Barbell Pullover", muscleGroup: "Back" },
  { id: "barbell-rear-delt-row", name: "Barbell Rear Delt Row", muscleGroup: "Shoulders" },
  { id: "barbell-reverse-lunge", name: "Barbell Reverse Lunge", muscleGroup: "Glutes" },
  { id: "barbell-row", name: "Bent-Over Barbell Row", muscleGroup: "Back" },
  { id: "barbell-wrist-curl", name: "Barbell Wrist Curl", muscleGroup: "Other" },
  { id: "battle-rope-double-slam", name: "Battle Rope Double Slam", muscleGroup: "Other" },
  { id: "battle-ropes", name: "Battle Ropes", muscleGroup: "Other" },
  { id: "bear-crawl", name: "Bear Crawl", muscleGroup: "Other" },
  { id: "behind-the-back-barbell-shrug", name: "Behind the Back Barbell Shrug", muscleGroup: "Back" },
  { id: "behind-the-neck-lat-pulldown", name: "Behind-the-Neck Lat Pulldown", muscleGroup: "Back" },
  { id: "behind-the-neck-press", name: "Behind the Neck Press", muscleGroup: "Shoulders" },
  { id: "behind-the-neck-pull-ups", name: "Behind-the-Neck Pull-Up", muscleGroup: "Back" },
  { id: "bench-adductor-stretch", name: "Bench Adductor Stretch", muscleGroup: "Other" },
  { id: "bench-ankle-stretch", name: "Bench Ankle Stretch", muscleGroup: "Calves" },
  { id: "bench-bulgarian-split-stretch", name: "Bench Bulgarian Split Stretch", muscleGroup: "Quads" },
  { id: "bench-calf-stretch", name: "Bench Calf Stretch", muscleGroup: "Calves" },
  { id: "bench-chest-stretch", name: "Bench Chest Stretch", muscleGroup: "Chest" },
  { id: "bench-childs-pose", name: "Bench Child's Pose", muscleGroup: "Back" },
  { id: "bench-couch-stretch", name: "Bench Couch Stretch", muscleGroup: "Quads" },
  { id: "bench-dips", name: "Bench Dips", muscleGroup: "Triceps" },
  { id: "bench-figure-4-glute-stretch", name: "Bench Figure-4 Glute Stretch", muscleGroup: "Glutes" },
  { id: "bench-hamstring-stretch", name: "Bench Hamstring Stretch", muscleGroup: "Hamstrings" },
  { id: "bench-lat-stretch", name: "Bench Lat Stretch", muscleGroup: "Back" },
  { id: "bench-leg-pull-in", name: "Bench Leg Pull-In", muscleGroup: "Abs" },
  { id: "bench-press", name: "Barbell Bench Press", muscleGroup: "Chest" },
  { id: "bench-pull", name: "Bench Pull", muscleGroup: "Back" },
  { id: "bent-arm-barbell-pullover", name: "Bent Arm Barbell Pullover", muscleGroup: "Back" },
  { id: "bent-arm-ez-bar-pullover", name: "Bent-Arm EZ-Bar Pullover", muscleGroup: "Back" },
  { id: "bent-over-db-row", name: "Bent-Over Dumbbell Row", muscleGroup: "Back" },
  { id: "bent-over-ez-bar-row", name: "Bent-Over EZ-Bar Row", muscleGroup: "Back" },
  { id: "bicep-curl", name: "Dumbbell Bicep Curl", muscleGroup: "Biceps" },
  { id: "bicycle-crunch", name: "Bicycle Crunch", muscleGroup: "Abs" },
  { id: "bird-dog", name: "Bird-Dog", muscleGroup: "Abs" },
  { id: "bird-dog-hold", name: "Bird Dog Hold", muscleGroup: "Abs" },
  { id: "boat-pose", name: "Boat Pose", muscleGroup: "Abs" },
  { id: "bodyweight-calf-raise", name: "Bodyweight Calf Raise", muscleGroup: "Calves" },
  { id: "bodyweight-good-morning", name: "Bodyweight Good Morning", muscleGroup: "Back" },
  { id: "bodyweight-lateral-raise", name: "Bodyweight Lateral Raise", muscleGroup: "Shoulders" },
  { id: "bodyweight-overhead-press", name: "Bodyweight Overhead Press", muscleGroup: "Shoulders" },
  { id: "bodyweight-reverse-lunge", name: "Bodyweight Reverse Lunge", muscleGroup: "Glutes" },
  { id: "bodyweight-squat", name: "Bodyweight Squat", muscleGroup: "Glutes" },
  { id: "bow-pose", name: "Bow Pose", muscleGroup: "Back" },
  { id: "box-jump", name: "Box Jump", muscleGroup: "Glutes" },
  { id: "box-squat", name: "Box Squat", muscleGroup: "Glutes" },
  { id: "bulgarian-split-squat", name: "Bulgarian Split Squat", muscleGroup: "Glutes" },
  { id: "burpees", name: "Burpees", muscleGroup: "Other" },
  { id: "butterfly-stretch", name: "Butterfly Stretch", muscleGroup: "Other" },
  { id: "cable-bent-over-row", name: "Cable Bent-Over Row", muscleGroup: "Back" },
  { id: "cable-chest-press", name: "Cable Chest Press", muscleGroup: "Chest" },
  { id: "cable-crunch", name: "Cable Crunch", muscleGroup: "Abs" },
  { id: "cable-curl", name: "Cable Curl", muscleGroup: "Biceps" },
  { id: "cable-external-rotation", name: "Cable External Rotation", muscleGroup: "Shoulders" },
  { id: "cable-fly", name: "Cable Fly", muscleGroup: "Chest" },
  { id: "cable-front-raise", name: "Cable Front Raise", muscleGroup: "Shoulders" },
  { id: "cable-hammer-curl", name: "Cable Hammer Curl", muscleGroup: "Biceps" },
  { id: "cable-kickback", name: "Cable Glute Kickback", muscleGroup: "Glutes" },
  { id: "cable-lateral-raise", name: "Cable Lateral Raise", muscleGroup: "Shoulders" },
  { id: "cable-pallof-press", name: "Cable Pallof Press", muscleGroup: "Abs" },
  { id: "cable-tricep-kickback", name: "Cable Tricep Kickback", muscleGroup: "Triceps" },
  { id: "cable-upright-row", name: "Cable Upright Row", muscleGroup: "Shoulders" },
  { id: "cable-wrist-curl", name: "Cable Wrist Curl", muscleGroup: "Other" },
  { id: "camel-pose", name: "Camel Pose", muscleGroup: "Abs" },
  { id: "captains-chair-knee-raise", name: "Captain's Chair Knee Raise", muscleGroup: "Abs" },
  { id: "captains-chair-leg-raise", name: "Captain's Chair Leg Raise", muscleGroup: "Abs" },
  { id: "cat-cow", name: "Cat-Cow", muscleGroup: "Back" },
  { id: "cat-stretch", name: "Cat Stretch", muscleGroup: "Back" },
  { id: "chair-pose", name: "Chair Pose", muscleGroup: "Glutes" },
  { id: "cheat-curl", name: "Cheat Curl", muscleGroup: "Biceps" },
  { id: "chest-press-machine", name: "Machine Chest Press", muscleGroup: "Chest" },
  { id: "chest-supported-db-row", name: "Chest-Supported Dumbbell Row", muscleGroup: "Back" },
  { id: "chest-supported-dumbbell-shrug", name: "Chest Supported Dumbbell Shrug", muscleGroup: "Back" },
  { id: "chest-supported-kettlebell-row", name: "Chest-Supported Kettlebell Row", muscleGroup: "Back" },
  { id: "chest-supported-smith-machine-row", name: "Chest-Supported Smith Machine Row", muscleGroup: "Back" },
  { id: "childs-pose", name: "Child's Pose", muscleGroup: "Back" },
  { id: "chin-tuck-hold", name: "Chin Tuck Hold", muscleGroup: "Other" },
  { id: "chin-ups", name: "Chin-Ups", muscleGroup: "Back" },
  { id: "clamshells", name: "Clamshells", muscleGroup: "Glutes" },
  { id: "clamshells-hold", name: "Clamshell Hold", muscleGroup: "Glutes" },
  { id: "clap-push-ups", name: "Clap Push-Ups", muscleGroup: "Chest" },
  { id: "clean", name: "Clean", muscleGroup: "Other" },
  { id: "clean-and-jerk", name: "Clean and Jerk", muscleGroup: "Other" },
  { id: "close-grip-barbell-curl", name: "Close-Grip Barbell Curl", muscleGroup: "Biceps" },
  { id: "close-grip-bench-press", name: "Close-Grip Bench Press", muscleGroup: "Triceps" },
  { id: "close-grip-db-bench-press", name: "Close-Grip Dumbbell Bench Press", muscleGroup: "Triceps" },
  { id: "close-grip-ez-bar-bench-press", name: "Close-Grip EZ-Bar Bench Press", muscleGroup: "Triceps" },
  { id: "close-grip-ez-bar-curl", name: "Close-Grip EZ-Bar Curl", muscleGroup: "Biceps" },
  { id: "close-grip-incline-bench", name: "Close-Grip Incline Bench Press", muscleGroup: "Triceps" },
  { id: "close-grip-lat-pulldown", name: "Close Grip Lat Pulldown", muscleGroup: "Back" },
  { id: "close-grip-pull-ups", name: "Close-Grip Pull-Ups", muscleGroup: "Back" },
  { id: "close-grip-push-ups", name: "Close Grip Push Ups", muscleGroup: "Chest" },
  { id: "close-stance-leg-press", name: "Close-Stance Leg Press", muscleGroup: "Quads" },
  { id: "cobra-stretch", name: "Cobra Stretch", muscleGroup: "Abs" },
  { id: "cocoons", name: "Cocoons", muscleGroup: "Abs" },
  { id: "concentration-curl", name: "Concentration Curl", muscleGroup: "Biceps" },
  { id: "cossack-squat", name: "Cossack Squat", muscleGroup: "Glutes" },
  { id: "cow-face-pose", name: "Cow Face Pose", muscleGroup: "Shoulders" },
  { id: "crab-dips", name: "Crab Dips", muscleGroup: "Triceps" },
  { id: "crescent-lunge", name: "Crescent Lunge", muscleGroup: "Glutes" },
  { id: "cross-body-crunch", name: "Cross-Body Crunch", muscleGroup: "Abs" },
  { id: "cross-body-hammer-curl", name: "Cross Body Hammer Curl", muscleGroup: "Biceps" },
  { id: "cross-body-shoulder-stretch", name: "Cross-Body Shoulder Stretch", muscleGroup: "Shoulders" },
  { id: "crow-pose", name: "Crow Pose", muscleGroup: "Triceps" },
  { id: "crunches", name: "Crunches", muscleGroup: "Abs" },
  { id: "dancer-pose", name: "Dancer Pose", muscleGroup: "Glutes" },
  { id: "db-bench-press", name: "Dumbbell Bench Press", muscleGroup: "Chest" },
  { id: "db-fly", name: "Dumbbell Fly", muscleGroup: "Chest" },
  { id: "db-kickstand-deadlift", name: "Dumbbell Kickstand Deadlift", muscleGroup: "Back" },
  { id: "db-lunge", name: "Dumbbell Lunge", muscleGroup: "Glutes" },
  { id: "db-overhead-carry", name: "Dumbbell Overhead Carry", muscleGroup: "Shoulders" },
  { id: "db-pullover", name: "Dumbbell Pullover", muscleGroup: "Chest" },
  { id: "db-reverse-curl", name: "Dumbbell Reverse Curl", muscleGroup: "Biceps" },
  { id: "db-reverse-wrist-curl", name: "Dumbbell Reverse Wrist Curl", muscleGroup: "Other" },
  { id: "db-shrug", name: "Dumbbell Shrug", muscleGroup: "Shoulders" },
  { id: "db-skull-crusher", name: "Dumbbell Skull Crusher", muscleGroup: "Triceps" },
  { id: "db-somersault-squat", name: "Dumbbell Somersault Squat", muscleGroup: "Glutes" },
  { id: "db-squat", name: "Dumbbell Squat", muscleGroup: "Glutes" },
  { id: "db-sumo-squat", name: "Dumbbell Sumo Squat", muscleGroup: "Glutes" },
  { id: "db-svend-press", name: "Dumbbell Svend Press", muscleGroup: "Chest" },
  { id: "dead-bug", name: "Dead Bug", muscleGroup: "Abs" },
  { id: "dead-bug-hold", name: "Dead Bug Hold", muscleGroup: "Abs" },
  { id: "dead-hang", name: "Dead Hang", muscleGroup: "Back" },
  { id: "deadlift", name: "Barbell Deadlift", muscleGroup: "Back" },
  { id: "decline-bench-press", name: "Decline Bench Press", muscleGroup: "Chest" },
  { id: "decline-bench-press-barbell", name: "Decline Barbell Bench Press", muscleGroup: "Chest" },
  { id: "decline-bench-press-ez-bar", name: "Decline EZ-Bar Bench Press", muscleGroup: "Chest" },
  { id: "decline-crunch", name: "Decline Crunch", muscleGroup: "Abs" },
  { id: "decline-db-fly", name: "Decline Dumbbell Fly", muscleGroup: "Chest" },
  { id: "decline-push-up", name: "Decline Push-Up", muscleGroup: "Chest" },
  { id: "deficit-deadlift", name: "Deficit Deadlift", muscleGroup: "Back" },
  { id: "deficit-push-ups", name: "Deficit Push Ups", muscleGroup: "Chest" },
  { id: "diamond-push-ups", name: "Diamond Push Ups", muscleGroup: "Chest" },
  { id: "dips", name: "Chest Dips", muscleGroup: "Chest" },
  { id: "dolphin-pose", name: "Dolphin Pose", muscleGroup: "Shoulders" },
  { id: "donkey-calf-raise", name: "Donkey Calf Raise", muscleGroup: "Calves" },
  { id: "doorway-chest-stretch", name: "Doorway Chest Stretch", muscleGroup: "Chest" },
  { id: "double-db-kickstand-deadlift", name: "Double Dumbbell Kickstand Deadlift", muscleGroup: "Back" },
  { id: "double-db-overhead-carry", name: "Double Dumbbell Overhead Carry", muscleGroup: "Shoulders" },
  { id: "double-kettlebell-bicep-curl", name: "Double Kettlebell Bicep Curl", muscleGroup: "Biceps" },
  { id: "double-kettlebell-clean", name: "Double Kettlebell Clean", muscleGroup: "Shoulders" },
  { id: "double-kettlebell-clean-and-press", name: "Double Kettlebell Clean and Press", muscleGroup: "Shoulders" },
  { id: "double-kettlebell-dead-clean", name: "Double Kettlebell Dead Clean", muscleGroup: "Other" },
  { id: "double-kettlebell-dead-split-snatch", name: "Double Kettlebell Dead Split Snatch", muscleGroup: "Other" },
  { id: "double-kettlebell-jerk", name: "Double Kettlebell Jerk", muscleGroup: "Shoulders" },
  { id: "double-kettlebell-overhead-carry", name: "Double Kettlebell Overhead Carry", muscleGroup: "Shoulders" },
  { id: "double-kettlebell-overhead-press", name: "Double Kettlebell Overhead Press", muscleGroup: "Shoulders" },
  { id: "double-kettlebell-push-press", name: "Double Kettlebell Push Press", muscleGroup: "Shoulders" },
  { id: "double-kettlebell-rear-delt-row", name: "Double Kettlebell Rear Delt Row", muscleGroup: "Shoulders" },
  { id: "double-kettlebell-row", name: "Double Kettlebell Row", muscleGroup: "Back" },
  { id: "double-kettlebell-split-jerk", name: "Double Kettlebell Split Jerk", muscleGroup: "Other" },
  { id: "double-kettlebell-swing-snatch", name: "Double Kettlebell Swing Snatch", muscleGroup: "Other" },
  { id: "downward-dog", name: "Downward-Facing Dog", muscleGroup: "Other" },
  { id: "downward-dog-knee-tuck", name: "Downward Dog Knee Tuck", muscleGroup: "Abs" },
  { id: "downward-dog-pedal", name: "Downward Dog Pedal", muscleGroup: "Calves" },
  { id: "downward-dog-to-knee-drive", name: "Downward Dog to Knee Drive", muscleGroup: "Abs" },
  { id: "downward-dog-to-low-lunge", name: "Downward Dog to Low Lunge", muscleGroup: "Other" },
  { id: "downward-dog-to-plank", name: "Downward Dog to Plank", muscleGroup: "Shoulders" },
  { id: "downward-dog-to-upward-dog", name: "Downward Dog to Upward Dog", muscleGroup: "Shoulders" },
  { id: "drag-curl", name: "Drag Curl", muscleGroup: "Biceps" },
  { id: "dragon-flag", name: "Dragon Flag", muscleGroup: "Abs" },
  { id: "dumbbell-bench-pull", name: "Dumbbell Bench Pull", muscleGroup: "Back" },
  { id: "dumbbell-calf-raise", name: "Dumbbell Calf Raise", muscleGroup: "Calves" },
  { id: "dumbbell-deadlift", name: "Dumbbell Deadlift", muscleGroup: "Back" },
  { id: "dumbbell-face-pull", name: "Dumbbell Face Pull", muscleGroup: "Back" },
  { id: "dumbbell-farmers-walk", name: "Dumbbell Farmer's Walk", muscleGroup: "Other" },
  { id: "dumbbell-floor-press", name: "Dumbbell Floor Press", muscleGroup: "Chest" },
  { id: "dumbbell-front-raise", name: "Dumbbell Front Raise", muscleGroup: "Shoulders" },
  { id: "dumbbell-front-squat", name: "Dumbbell Front Squat", muscleGroup: "Glutes" },
  { id: "dumbbell-hip-thrust", name: "Dumbbell Hip Thrust", muscleGroup: "Glutes" },
  { id: "dumbbell-pistol-squat", name: "Dumbbell Pistol Squat", muscleGroup: "Glutes" },
  { id: "dumbbell-push-press", name: "Dumbbell Push Press", muscleGroup: "Shoulders" },
  { id: "dumbbell-reverse-fly", name: "Dumbbell Reverse Fly", muscleGroup: "Shoulders" },
  { id: "dumbbell-romanian-deadlift", name: "Dumbbell Romanian Deadlift", muscleGroup: "Back" },
  { id: "dumbbell-shoulder-press", name: "Dumbbell Shoulder Press", muscleGroup: "Shoulders" },
  { id: "dumbbell-side-bend", name: "Dumbbell Side Bend", muscleGroup: "Abs" },
  { id: "dumbbell-snatch", name: "Dumbbell Snatch", muscleGroup: "Other" },
  { id: "dumbbell-split-squat", name: "Dumbbell Split Squat", muscleGroup: "Glutes" },
  { id: "dumbbell-tricep-extension", name: "Dumbbell Tricep Extension", muscleGroup: "Triceps" },
  { id: "dumbbell-upright-row", name: "Dumbbell Upright Row", muscleGroup: "Shoulders" },
  { id: "dumbbell-windmill", name: "Dumbbell Windmill", muscleGroup: "Other" },
  { id: "dumbbell-wrist-curl", name: "Dumbbell Wrist Curl", muscleGroup: "Other" },
  { id: "eagle-pose", name: "Eagle Pose", muscleGroup: "Glutes" },
  { id: "easy-pose", name: "Easy Pose", muscleGroup: "Other" },
  { id: "elliptical-trainer", name: "Elliptical Trainer", muscleGroup: "Other" },
  { id: "extended-side-angle", name: "Extended Side Angle Pose", muscleGroup: "Quads" },
  { id: "ez-bar-bench-press", name: "EZ-Bar Bench Press", muscleGroup: "Chest" },
  { id: "ez-bar-curl", name: "EZ-Bar Curl", muscleGroup: "Biceps" },
  { id: "ez-bar-front-raise", name: "EZ-Bar Front Raise", muscleGroup: "Shoulders" },
  { id: "ez-bar-lying-tricep-extension", name: "EZ-Bar Lying Triceps Extension", muscleGroup: "Triceps" },
  { id: "ez-bar-overhead-extension", name: "EZ-Bar Overhead Tricep Extension", muscleGroup: "Triceps" },
  { id: "ez-bar-pullover", name: "EZ Bar Pullover", muscleGroup: "Back" },
  { id: "ez-bar-reverse-curl", name: "EZ-Bar Reverse Curl", muscleGroup: "Biceps" },
  { id: "ez-bar-reverse-grip-row", name: "EZ Bar Reverse Grip Row", muscleGroup: "Back" },
  { id: "ez-bar-romanian-deadlift", name: "EZ-Bar Romanian Deadlift", muscleGroup: "Hamstrings" },
  { id: "ez-bar-shrug", name: "EZ-Bar Shrug", muscleGroup: "Shoulders" },
  { id: "ez-bar-spider-curl", name: "EZ Bar Spider Curl", muscleGroup: "Biceps" },
  { id: "ez-bar-upright-row", name: "EZ-Bar Upright Row", muscleGroup: "Shoulders" },
  { id: "ez-bar-wrist-curl", name: "EZ-Bar Wrist Curl", muscleGroup: "Other" },
  { id: "face-pull", name: "Cable Face Pull", muscleGroup: "Shoulders" },
  { id: "fish-pose", name: "Fish Pose", muscleGroup: "Chest" },
  { id: "floor-ez-bar-press", name: "Floor EZ-Bar Press", muscleGroup: "Chest" },
  { id: "floor-kettlebell-pullover", name: "Floor Kettlebell Pullover", muscleGroup: "Back" },
  { id: "floor-press", name: "Floor Press", muscleGroup: "Chest" },
  { id: "flutter-kicks", name: "Flutter Kicks", muscleGroup: "Abs" },
  { id: "front-lever", name: "Front Lever", muscleGroup: "Back" },
  { id: "front-squat", name: "Front Squat", muscleGroup: "Glutes" },
  { id: "garland-pose", name: "Garland Pose", muscleGroup: "Glutes" },
  { id: "glute-bridge", name: "Glute Bridge", muscleGroup: "Glutes" },
  { id: "glute-bridge-hold", name: "Glute Bridge Hold", muscleGroup: "Glutes" },
  { id: "glute-kickback", name: "Glute Kickback", muscleGroup: "Glutes" },
  { id: "glute-kickback-hold", name: "Glute Kickback Hold", muscleGroup: "Glutes" },
  { id: "goblet-squat", name: "Goblet Squat", muscleGroup: "Glutes" },
  { id: "good-morning", name: "Good Morning", muscleGroup: "Hamstrings" },
  { id: "hack-squat", name: "Hack Squat", muscleGroup: "Glutes" },
  { id: "hack-squat-calf-raise", name: "Hack Squat Calf Raise", muscleGroup: "Calves" },
  { id: "half-kneeling-hip-flexor-rock", name: "Half-Kneeling Hip Flexor Rock", muscleGroup: "Other" },
  { id: "half-moon-pose", name: "Half Moon Pose", muscleGroup: "Abs" },
  { id: "hammer-curl", name: "Dumbbell Hammer Curl", muscleGroup: "Biceps" },
  { id: "handstand-push-ups", name: "Handstand Push Ups", muscleGroup: "Shoulders" },
  { id: "hang-clean", name: "Hang Clean", muscleGroup: "Other" },
  { id: "hang-power-clean", name: "Hang Power Clean", muscleGroup: "Other" },
  { id: "hanging-knee-raise", name: "Hanging Knee Raise", muscleGroup: "Abs" },
  { id: "hanging-leg-raise", name: "Hanging Leg Raise", muscleGroup: "Abs" },
  { id: "hanging-pike", name: "Hanging Pike", muscleGroup: "Abs" },
  { id: "happy-baby", name: "Happy Baby Pose", muscleGroup: "Glutes" },
  { id: "head-to-knee-pose", name: "Head-to-Knee Pose", muscleGroup: "Hamstrings" },
  { id: "heel-elevated-squat", name: "Heel-Elevated Squat", muscleGroup: "Glutes" },
  { id: "heel-to-toe-walk", name: "Heel-to-Toe Walk", muscleGroup: "Calves" },
  { id: "hero-pose", name: "Hero Pose", muscleGroup: "Quads" },
  { id: "hex-bar-deadlift", name: "Hex Bar Deadlift", muscleGroup: "Back" },
  { id: "high-foot-leg-press", name: "High-Foot Leg Press", muscleGroup: "Glutes" },
  { id: "high-knees", name: "High Knees", muscleGroup: "Other" },
  { id: "high-plank", name: "High Plank", muscleGroup: "Abs" },
  { id: "hip-abduction", name: "Machine Hip Abduction", muscleGroup: "Glutes" },
  { id: "hip-adduction", name: "Hip Adduction", muscleGroup: "Other" },
  { id: "hip-thrust", name: "Barbell Hip Thrust", muscleGroup: "Glutes" },
  { id: "hollow-body-hold", name: "Hollow Body Hold", muscleGroup: "Abs" },
  { id: "horizontal-leg-press", name: "Horizontal Leg Press", muscleGroup: "Glutes" },
  { id: "human-flag", name: "Human Flag", muscleGroup: "Abs" },
  { id: "incline-bench-ez-bar-press", name: "Incline EZ-Bar Bench Press", muscleGroup: "Chest" },
  { id: "incline-bench-press", name: "Incline Barbell Bench Press", muscleGroup: "Chest" },
  { id: "incline-db-curl", name: "Incline Dumbbell Curl", muscleGroup: "Biceps" },
  { id: "incline-db-press", name: "Incline Dumbbell Press", muscleGroup: "Chest" },
  { id: "incline-dumbbell-fly", name: "Incline Dumbbell Fly", muscleGroup: "Chest" },
  { id: "incline-hammer-curl", name: "Incline Hammer Curl", muscleGroup: "Biceps" },
  { id: "incline-push-ups", name: "Incline Push-Up", muscleGroup: "Chest" },
  { id: "incline-treadmill-walk", name: "Incline Treadmill Walk", muscleGroup: "Other" },
  { id: "inverted-row", name: "Inverted Row", muscleGroup: "Back" },
  { id: "isometric-neck-side", name: "Isometric Neck Lateral Flexion", muscleGroup: "Shoulders" },
  { id: "jackknife-sit-up", name: "Jackknife Sit-Up", muscleGroup: "Abs" },
  { id: "jefferson-curl", name: "Jefferson Curl", muscleGroup: "Back" },
  { id: "jump-rope", name: "Jump Rope", muscleGroup: "Other" },
  { id: "jump-squat", name: "Jump Squat", muscleGroup: "Glutes" },
  { id: "jumping-jacks", name: "Jumping Jacks", muscleGroup: "Other" },
  { id: "kettlebell-bulgarian-split-squat", name: "Kettlebell Bulgarian Split Squat", muscleGroup: "Glutes" },
  { id: "kettlebell-close-grip-floor-press", name: "Kettlebell Close-Grip Floor Press", muscleGroup: "Triceps" },
  { id: "kettlebell-concentration-curl", name: "Kettlebell Concentration Curl", muscleGroup: "Biceps" },
  { id: "kettlebell-deadlift", name: "Kettlebell Deadlift", muscleGroup: "Back" },
  { id: "kettlebell-farmers-walk", name: "Kettlebell Farmer's Walk", muscleGroup: "Other" },
  { id: "kettlebell-floor-press", name: "Kettlebell Floor Press", muscleGroup: "Chest" },
  { id: "kettlebell-goblet-lunge", name: "Kettlebell Goblet Lunge", muscleGroup: "Glutes" },
  { id: "kettlebell-halo", name: "Kettlebell Halo", muscleGroup: "Shoulders" },
  { id: "kettlebell-hammer-curl", name: "Kettlebell Hammer Curl", muscleGroup: "Biceps" },
  { id: "kettlebell-hip-thrust", name: "Kettlebell Hip Thrust", muscleGroup: "Glutes" },
  { id: "kettlebell-kickstand-deadlift", name: "Kettlebell Kickstand Deadlift", muscleGroup: "Back" },
  { id: "kettlebell-lunge-press", name: "Kettlebell Lunge Press", muscleGroup: "Other" },
  { id: "kettlebell-offset-reverse-lunge-and-press", name: "Kettlebell Offset Reverse Lunge and Press", muscleGroup: "Other" },
  { id: "kettlebell-overhead-carry", name: "Kettlebell Overhead Carry", muscleGroup: "Shoulders" },
  { id: "kettlebell-overhead-tricep-extension", name: "Kettlebell Overhead Tricep Extension", muscleGroup: "Triceps" },
  { id: "kettlebell-pistol-squat", name: "Kettlebell Pistol Squat", muscleGroup: "Glutes" },
  { id: "kettlebell-pullover", name: "Kettlebell Pullover", muscleGroup: "Back" },
  { id: "kettlebell-reverse-lunge", name: "Kettlebell Reverse Lunge", muscleGroup: "Glutes" },
  { id: "kettlebell-reverse-wrist-curl", name: "Kettlebell Reverse Wrist Curl", muscleGroup: "Other" },
  { id: "kettlebell-rotational-lunge", name: "Kettlebell Rotational Lunge", muscleGroup: "Glutes" },
  { id: "kettlebell-russian-twist", name: "Kettlebell Russian Twist", muscleGroup: "Abs" },
  { id: "kettlebell-shrug", name: "Kettlebell Shrug", muscleGroup: "Back" },
  { id: "kettlebell-single-leg-deadlift", name: "Kettlebell Single Leg Deadlift", muscleGroup: "Back" },
  { id: "kettlebell-skull-crusher", name: "Kettlebell Skull Crusher", muscleGroup: "Triceps" },
  { id: "kettlebell-squat", name: "Kettlebell Squat", muscleGroup: "Quads" },
  { id: "kettlebell-sumo-deadlift", name: "Kettlebell Sumo Deadlift", muscleGroup: "Glutes" },
  { id: "kettlebell-sumo-high-pull", name: "Kettlebell Sumo High Pull", muscleGroup: "Shoulders" },
  { id: "kettlebell-svend-press", name: "Kettlebell Svend Press", muscleGroup: "Chest" },
  { id: "kettlebell-swing", name: "Kettlebell Swing", muscleGroup: "Hamstrings" },
  { id: "kettlebell-swing-clean", name: "Kettlebell Swing Clean", muscleGroup: "Other" },
  { id: "kettlebell-turkish-get-ups", name: "Kettlebell Turkish Get Ups", muscleGroup: "Other" },
  { id: "kettlebell-windmills", name: "Kettlebell Windmills", muscleGroup: "Other" },
  { id: "kettlebell-wrist-curl", name: "Kettlebell Wrist Curl", muscleGroup: "Other" },
  { id: "knee-push-ups", name: "Knee Push Ups", muscleGroup: "Chest" },
  { id: "knee-to-chest-stretch", name: "Knee-to-Chest Stretch", muscleGroup: "Glutes" },
  { id: "kneeling-cable-row", name: "Kneeling Cable Row", muscleGroup: "Back" },
  { id: "kneeling-hip-flexor-stretch", name: "Kneeling Hip Flexor Stretch", muscleGroup: "Other" },
  { id: "kneeling-wrist-stretch", name: "Kneeling Wrist Stretch", muscleGroup: "Other" },
  { id: "l-sit", name: "L Sit", muscleGroup: "Other" },
  { id: "landmine-press", name: "Landmine Press", muscleGroup: "Shoulders" },
  { id: "lat-pulldown", name: "Lat Pulldown", muscleGroup: "Back" },
  { id: "lateral-raise", name: "Dumbbell Lateral Raise", muscleGroup: "Shoulders" },
  { id: "leg-curl", name: "Lying Leg Curl", muscleGroup: "Hamstrings" },
  { id: "leg-extension", name: "Leg Extension", muscleGroup: "Quads" },
  { id: "leg-press", name: "Leg Press", muscleGroup: "Glutes" },
  { id: "legs-up-the-wall", name: "Legs-Up-the-Wall Pose", muscleGroup: "Hamstrings" },
  { id: "lizard-stretch", name: "Lizard Stretch", muscleGroup: "Other" },
  { id: "locust-pose", name: "Locust Pose", muscleGroup: "Back" },
  { id: "low-lunge", name: "Low Lunge", muscleGroup: "Quads" },
  { id: "low-lunge-to-half-split", name: "Low Lunge to Half Split", muscleGroup: "Hamstrings" },
  { id: "lunge", name: "Lunge", muscleGroup: "Glutes" },
  { id: "lying-leg-raise", name: "Lying Leg Raise", muscleGroup: "Abs" },
  { id: "lying-tricep-extension", name: "Lying Tricep Extension", muscleGroup: "Triceps" },
  { id: "machine-back-extension", name: "Machine Back Extension", muscleGroup: "Back" },
  { id: "machine-bicep-curl", name: "Machine Bicep Curl", muscleGroup: "Biceps" },
  { id: "machine-calf-raise", name: "Machine Calf Raise", muscleGroup: "Calves" },
  { id: "machine-chest-fly", name: "Machine Chest Fly", muscleGroup: "Chest" },
  { id: "machine-preacher-curl", name: "Machine Preacher Curl", muscleGroup: "Biceps" },
  { id: "machine-seated-crunch", name: "Machine Seated Crunch", muscleGroup: "Abs" },
  { id: "machine-shoulder-press", name: "Machine Shoulder Press", muscleGroup: "Shoulders" },
  { id: "machine-triceps-extension", name: "Machine Triceps Extension", muscleGroup: "Triceps" },
  { id: "medicine-ball-slam", name: "Medicine Ball Slam", muscleGroup: "Abs" },
  { id: "mountain-climbers", name: "Mountain Climbers", muscleGroup: "Abs" },
  { id: "mountain-pose", name: "Mountain Pose", muscleGroup: "Other" },
  { id: "muscle-snatch", name: "Muscle Snatch", muscleGroup: "Other" },
  { id: "muscle-ups", name: "Muscle Ups", muscleGroup: "Back" },
  { id: "neck-side-stretch", name: "Neck Side Stretch", muscleGroup: "Back" },
  { id: "negative-pull-ups", name: "Negative Pull Ups", muscleGroup: "Back" },
  { id: "neutral-grip-pull-ups", name: "Neutral Grip Pull Ups", muscleGroup: "Back" },
  { id: "nordic-hamstring-curl", name: "Nordic Hamstring Curl", muscleGroup: "Hamstrings" },
  { id: "ohp", name: "Barbell Overhead Press", muscleGroup: "Shoulders" },
  { id: "one-arm-dumbbell-push-press", name: "One-Arm Dumbbell Push Press", muscleGroup: "Shoulders" },
  { id: "one-arm-dumbbell-swing", name: "One-Arm Dumbbell Swing", muscleGroup: "Other" },
  { id: "one-arm-kettlebell-bicep-curl", name: "One Arm Kettlebell Bicep Curl", muscleGroup: "Biceps" },
  { id: "one-arm-kettlebell-bottoms-up-press", name: "One-Arm Kettlebell Bottoms-Up Press", muscleGroup: "Shoulders" },
  { id: "one-arm-kettlebell-floor-glute-bridge-press", name: "One Arm Kettlebell Floor Glute Bridge Press", muscleGroup: "Chest" },
  { id: "one-arm-kettlebell-floor-press", name: "One Arm Kettlebell Floor Press", muscleGroup: "Chest" },
  { id: "one-arm-kettlebell-front-squat", name: "One Arm Kettlebell Front Squat", muscleGroup: "Glutes" },
  { id: "one-arm-kettlebell-push-press", name: "One Arm Kettlebell Push Press", muscleGroup: "Shoulders" },
  { id: "one-arm-kettlebell-row", name: "One Arm Kettlebell Row", muscleGroup: "Back" },
  { id: "one-arm-kettlebell-shoulder-press", name: "One Arm Kettlebell Shoulder Press", muscleGroup: "Shoulders" },
  { id: "one-arm-kettlebell-swing", name: "One Arm Kettlebell Swing", muscleGroup: "Other" },
  { id: "one-arm-kettlebell-tricep-kickback", name: "One-Arm Kettlebell Tricep Kickback", muscleGroup: "Triceps" },
  { id: "one-arm-landmine-press", name: "One-Arm Landmine Press", muscleGroup: "Shoulders" },
  { id: "one-arm-lat-pulldown", name: "One-Arm Lat Pulldown", muscleGroup: "Back" },
  { id: "one-arm-single-leg-dumbbell-romanian-deadlift", name: "One-Arm Single-Leg Dumbbell Romanian Deadlift", muscleGroup: "Hamstrings" },
  { id: "one-arm-single-leg-kettlebell-romanian-deadlift", name: "One-Arm Single-Leg Kettlebell Romanian Deadlift", muscleGroup: "Hamstrings" },
  { id: "overhead-squat", name: "Overhead Squat", muscleGroup: "Glutes" },
  { id: "overhead-tricep-extension", name: "Overhead Tricep Extension", muscleGroup: "Triceps" },
  { id: "overhead-triceps-stretch", name: "Overhead Triceps Stretch", muscleGroup: "Triceps" },
  { id: "pause-deadlift", name: "Pause Deadlift", muscleGroup: "Back" },
  { id: "pause-pull-up", name: "Pause Pull-Up", muscleGroup: "Back" },
  { id: "pause-squat", name: "Pause Squat", muscleGroup: "Glutes" },
  { id: "paused-bench-press", name: "Paused Bench Press", muscleGroup: "Chest" },
  { id: "paused-incline-bench-press", name: "Paused Incline Bench Press", muscleGroup: "Chest" },
  { id: "paused-ohp", name: "Paused Overhead Press", muscleGroup: "Shoulders" },
  { id: "pec-deck", name: "Pec Deck", muscleGroup: "Chest" },
  { id: "pendlay-row", name: "Pendlay Row", muscleGroup: "Back" },
  { id: "pigeon-stretch", name: "Pigeon Stretch", muscleGroup: "Glutes" },
  { id: "pike-push-ups", name: "Pike Push Ups", muscleGroup: "Shoulders" },
  { id: "pilates-kneeling-side-kick", name: "Pilates Kneeling Side Kick", muscleGroup: "Glutes" },
  { id: "pilates-leg-pull-back", name: "Pilates Leg Pull Back", muscleGroup: "Abs" },
  { id: "pilates-leg-pull-front", name: "Pilates Leg Pull Front", muscleGroup: "Abs" },
  { id: "pilates-roll-down", name: "Pilates Roll Down", muscleGroup: "Back" },
  { id: "pilates-roll-over", name: "Pilates Roll Over", muscleGroup: "Abs" },
  { id: "pilates-saw", name: "Pilates Saw", muscleGroup: "Back" },
  { id: "pilates-side-bend", name: "Pilates Side Bend", muscleGroup: "Abs" },
  { id: "pilates-spine-stretch-forward", name: "Pilates Spine Stretch Forward", muscleGroup: "Back" },
  { id: "pilates-spine-twist", name: "Pilates Spine Twist", muscleGroup: "Abs" },
  { id: "pistol-squat", name: "Pistol Squat", muscleGroup: "Glutes" },
  { id: "planche", name: "Planche", muscleGroup: "Chest" },
  { id: "plank", name: "Plank", muscleGroup: "Abs" },
  { id: "plate-loaded-donkey-calf-raise", name: "Plate-Loaded Donkey Calf Raise", muscleGroup: "Calves" },
  { id: "plate-loaded-glute-drive", name: "Plate-Loaded Glute Drive", muscleGroup: "Glutes" },
  { id: "plate-loaded-lateral-raise", name: "Plate-Loaded Lateral Raise", muscleGroup: "Shoulders" },
  { id: "plate-loaded-shrug", name: "Plate-Loaded Shrug", muscleGroup: "Back" },
  { id: "plate-pinch", name: "Plate Pinch", muscleGroup: "Other" },
  { id: "plate-pullover", name: "Plate Pullover", muscleGroup: "Back" },
  { id: "plow-pose", name: "Plow Pose", muscleGroup: "Back" },
  { id: "plyo-lunge", name: "Plyo Lunge", muscleGroup: "Glutes" },
  { id: "plyo-push-up", name: "Plyo Push-Up", muscleGroup: "Chest" },
  { id: "preacher-curl", name: "Preacher Curl", muscleGroup: "Biceps" },
  { id: "preacher-hammer-curl", name: "Preacher Hammer Curl", muscleGroup: "Biceps" },
  { id: "pseudo-planche-push-ups", name: "Pseudo Planche Push Ups", muscleGroup: "Chest" },
  { id: "pull-up", name: "Pull-Up", muscleGroup: "Back" },
  { id: "puppy-pose", name: "Puppy Pose", muscleGroup: "Shoulders" },
  { id: "push-jerk", name: "Push Jerk", muscleGroup: "Other" },
  { id: "push-press", name: "Push Press", muscleGroup: "Shoulders" },
  { id: "push-up", name: "Push-Up", muscleGroup: "Chest" },
  { id: "pyramid-pose", name: "Pyramid Pose", muscleGroup: "Hamstrings" },
  { id: "rack-pull", name: "Rack Pull", muscleGroup: "Back" },
  { id: "rear-delt-fly", name: "Rear Delt Fly", muscleGroup: "Shoulders" },
  { id: "reverse-crunches", name: "Reverse Crunches", muscleGroup: "Abs" },
  { id: "reverse-curl", name: "Reverse Curl", muscleGroup: "Biceps" },
  { id: "reverse-grip-bent-over-row", name: "Reverse Grip Bent Over Row", muscleGroup: "Back" },
  { id: "reverse-grip-lat-pulldown", name: "Reverse Grip Lat Pulldown", muscleGroup: "Back" },
  { id: "reverse-lunge", name: "Reverse Lunge", muscleGroup: "Glutes" },
  { id: "reverse-nordic-curl", name: "Reverse Nordic Curl", muscleGroup: "Quads" },
  { id: "reverse-plank", name: "Reverse Plank", muscleGroup: "Abs" },
  { id: "reverse-plank-dips", name: "Reverse Plank Dips", muscleGroup: "Triceps" },
  { id: "reverse-tabletop-hip-pulses", name: "Reverse Tabletop Hip Pulses", muscleGroup: "Glutes" },
  { id: "reverse-tabletop-hold", name: "Reverse Tabletop Hold", muscleGroup: "Abs" },
  { id: "revolved-chair-pose", name: "Revolved Chair Pose", muscleGroup: "Abs" },
  { id: "revolved-crescent-lunge", name: "Revolved Crescent Lunge", muscleGroup: "Abs" },
  { id: "ring-dead-hang", name: "Ring Dead Hang", muscleGroup: "Back" },
  { id: "ring-dips", name: "Ring Dips", muscleGroup: "Chest" },
  { id: "ring-face-pull", name: "Ring Face Pull", muscleGroup: "Back" },
  { id: "ring-muscle-up", name: "Ring Muscle-Up", muscleGroup: "Back" },
  { id: "ring-push-up", name: "Ring Push-Up", muscleGroup: "Chest" },
  { id: "ring-row", name: "Ring Row", muscleGroup: "Back" },
  { id: "rings-inverted-row", name: "Rings Inverted Row", muscleGroup: "Back" },
  { id: "romanian-deadlift", name: "Romanian Deadlift", muscleGroup: "Hamstrings" },
  { id: "rope-climb", name: "Rope Climb", muscleGroup: "Back" },
  { id: "rowing-machine", name: "Rowing Machine", muscleGroup: "Other" },
  { id: "running", name: "Running", muscleGroup: "Other" },
  { id: "russian-twist", name: "Russian Twist", muscleGroup: "Abs" },
  { id: "savasana", name: "Corpse Pose", muscleGroup: "Other" },
  { id: "scapular-pull-ups", name: "Scapular Pull Ups", muscleGroup: "Back" },
  { id: "scissor-kicks", name: "Scissor Kicks", muscleGroup: "Abs" },
  { id: "seated-barbell-overhead-press", name: "Seated Barbell Overhead Press", muscleGroup: "Shoulders" },
  { id: "seated-cable-row", name: "Seated Cable Row", muscleGroup: "Back" },
  { id: "seated-calf-raise", name: "Seated Calf Raise", muscleGroup: "Calves" },
  { id: "seated-db-press", name: "Seated Dumbbell Shoulder Press", muscleGroup: "Shoulders" },
  { id: "seated-dumbbell-curl", name: "Seated Dumbbell Curl", muscleGroup: "Biceps" },
  { id: "seated-dumbbell-lateral-raise", name: "Seated Dumbbell Lateral Raise", muscleGroup: "Shoulders" },
  { id: "seated-dumbbell-tricep-extension", name: "Seated Dumbbell Tricep Extension", muscleGroup: "Triceps" },
  { id: "seated-forward-fold", name: "Seated Forward Fold", muscleGroup: "Hamstrings" },
  { id: "seated-leg-curl", name: "Seated Leg Curl", muscleGroup: "Hamstrings" },
  { id: "seated-smith-machine-shoulder-press", name: "Seated Smith Machine Shoulder Press", muscleGroup: "Shoulders" },
  { id: "seated-spinal-twist", name: "Seated Spinal Twist", muscleGroup: "Back" },
  { id: "seated-straddle-stretch", name: "Seated Straddle Stretch", muscleGroup: "Hamstrings" },
  { id: "shrug", name: "Barbell Shrug", muscleGroup: "Shoulders" },
  { id: "side-lunge", name: "Side Lunge", muscleGroup: "Glutes" },
  { id: "side-lying-hip-abduction", name: "Side-Lying Hip Abduction", muscleGroup: "Glutes" },
  { id: "side-lying-hip-abduction-hold", name: "Side-Lying Hip Abduction Hold", muscleGroup: "Glutes" },
  { id: "side-lying-hip-adduction", name: "Side Lying Hip Adduction", muscleGroup: "Other" },
  { id: "side-lying-hip-adduction-hold", name: "Side-Lying Hip Adduction Hold", muscleGroup: "Other" },
  { id: "side-lying-lateral-raise", name: "Side-Lying Lateral Raise", muscleGroup: "Shoulders" },
  { id: "side-plank", name: "Side Plank", muscleGroup: "Abs" },
  { id: "side-plank-leg-lift", name: "Side Plank with Leg Lift", muscleGroup: "Abs" },
  { id: "side-plank-leg-lift-hold", name: "Side Plank Leg Lift Hold", muscleGroup: "Abs" },
  { id: "single-arm-chest-supported-dumbbell-row", name: "Single-Arm Chest-Supported Dumbbell Row", muscleGroup: "Back" },
  { id: "single-arm-db-row", name: "Single-Arm Dumbbell Row", muscleGroup: "Back" },
  { id: "single-arm-dumbbell-overhead-tricep-extension", name: "Single-Arm Dumbbell Overhead Tricep Extension", muscleGroup: "Triceps" },
  { id: "single-arm-hammer-curl", name: "Single-Arm Hammer Curl", muscleGroup: "Biceps" },
  { id: "single-arm-machine-shoulder-press", name: "Single-Arm Machine Shoulder Press", muscleGroup: "Shoulders" },
  { id: "single-arm-plate-loaded-lateral-raise", name: "Single-Arm Plate-Loaded Lateral Raise", muscleGroup: "Shoulders" },
  { id: "single-arm-tricep-pushdown", name: "Single Arm Tricep Pushdown", muscleGroup: "Triceps" },
  { id: "single-db-svend-press", name: "Single Dumbbell Svend Press", muscleGroup: "Chest" },
  { id: "single-leg-calf-raise", name: "Single Leg Calf Raise", muscleGroup: "Calves" },
  { id: "single-leg-extension", name: "Single Leg Extension", muscleGroup: "Quads" },
  { id: "single-leg-glute-bridge", name: "Single Leg Glute Bridge", muscleGroup: "Glutes" },
  { id: "single-leg-glute-bridge-hold", name: "Single-Leg Glute Bridge Hold", muscleGroup: "Glutes" },
  { id: "single-leg-lying-leg-curl", name: "Single Leg Lying Leg Curl", muscleGroup: "Hamstrings" },
  { id: "single-leg-press", name: "Single Leg Press", muscleGroup: "Glutes" },
  { id: "single-leg-romanian-deadlift", name: "Single Leg Romanian Deadlift", muscleGroup: "Back" },
  { id: "sit-ups", name: "Sit-Ups", muscleGroup: "Abs" },
  { id: "skull-crusher", name: "Skull Crusher", muscleGroup: "Triceps" },
  { id: "sled-row", name: "Sled Row", muscleGroup: "Back" },
  { id: "smith-machine-bench-press", name: "Smith Machine Bench Press", muscleGroup: "Chest" },
  { id: "smith-machine-bent-over-row", name: "Smith Machine Bent Over Row", muscleGroup: "Back" },
  { id: "smith-machine-bulgarian-split", name: "Smith Machine Bulgarian Split Squat", muscleGroup: "Glutes" },
  { id: "smith-machine-calf-raise", name: "Smith Machine Calf Raise", muscleGroup: "Calves" },
  { id: "smith-machine-decline-bench-press", name: "Smith Machine Decline Bench Press", muscleGroup: "Chest" },
  { id: "smith-machine-front-squat", name: "Smith Machine Front Squat", muscleGroup: "Glutes" },
  { id: "smith-machine-good-morning", name: "Smith Machine Good Morning", muscleGroup: "Hamstrings" },
  { id: "smith-machine-hip-thrust", name: "Smith Machine Hip Thrust", muscleGroup: "Glutes" },
  { id: "smith-machine-incline-bench-press", name: "Smith Machine Incline Bench Press", muscleGroup: "Chest" },
  { id: "smith-machine-rdl", name: "Smith Machine Romanian Deadlift", muscleGroup: "Hamstrings" },
  { id: "smith-machine-reverse-grip-bent-over-row", name: "Smith Machine Reverse Grip Bent Over Row", muscleGroup: "Back" },
  { id: "smith-machine-reverse-lunge", name: "Smith Machine Reverse Lunge", muscleGroup: "Glutes" },
  { id: "smith-machine-shoulder-press", name: "Smith Machine Shoulder Press", muscleGroup: "Shoulders" },
  { id: "smith-machine-shrug", name: "Smith Machine Shrug", muscleGroup: "Back" },
  { id: "smith-machine-split-squat", name: "Smith Machine Split Squat", muscleGroup: "Glutes" },
  { id: "smith-machine-squat", name: "Smith Machine Squat", muscleGroup: "Glutes" },
  { id: "smith-machine-upright-row", name: "Smith Machine Upright Row", muscleGroup: "Shoulders" },
  { id: "snatch", name: "Snatch", muscleGroup: "Other" },
  { id: "sphinx-pose", name: "Sphinx Pose", muscleGroup: "Abs" },
  { id: "spider-curl", name: "Spider Curl", muscleGroup: "Biceps" },
  { id: "split-jerk", name: "Split Jerk", muscleGroup: "Other" },
  { id: "split-squat", name: "Split Squat", muscleGroup: "Glutes" },
  { id: "spoto-press", name: "Spoto Press", muscleGroup: "Chest" },
  { id: "squat", name: "Barbell Back Squat", muscleGroup: "Glutes" },
  { id: "stability-ball-hip-bridge", name: "Stability Ball Hip Bridge", muscleGroup: "Glutes" },
  { id: "stability-ball-knee-tuck", name: "Stability Ball Knee Tuck", muscleGroup: "Abs" },
  { id: "stability-ball-push-up", name: "Stability Ball Push-Up", muscleGroup: "Chest" },
  { id: "stability-ball-push-up-hands-on-ball", name: "Stability Ball Push-Up (Hands on Ball)", muscleGroup: "Chest" },
  { id: "stability-ball-wall-squat", name: "Stability Ball Wall Squat", muscleGroup: "Glutes" },
  { id: "stair-climber", name: "Stair Climber", muscleGroup: "Glutes" },
  { id: "standing-calf-raise", name: "Standing Calf Raise", muscleGroup: "Calves" },
  { id: "standing-calf-stretch", name: "Standing Calf Stretch", muscleGroup: "Calves" },
  { id: "standing-forward-fold", name: "Standing Forward Fold", muscleGroup: "Hamstrings" },
  { id: "standing-forward-fold-to-half-lift", name: "Standing Forward Fold to Half Lift", muscleGroup: "Hamstrings" },
  { id: "standing-quad-stretch", name: "Standing Quad Stretch", muscleGroup: "Quads" },
  { id: "standing-side-bend", name: "Standing Side Bend", muscleGroup: "Abs" },
  { id: "standing-side-bend-flow", name: "Standing Side Bend Flow", muscleGroup: "Abs" },
  { id: "standing-split", name: "Standing Split", muscleGroup: "Hamstrings" },
  { id: "stationary-bike", name: "Stationary Bike", muscleGroup: "Quads" },
  { id: "step-ups", name: "Step Ups", muscleGroup: "Glutes" },
  { id: "stiff-leg-deadlift", name: "Stiff Leg Deadlift", muscleGroup: "Back" },
  { id: "straight-arm-pulldown", name: "Straight-Arm Pulldown", muscleGroup: "Back" },
  { id: "straight-bar-cable-front-raise", name: "Straight-Bar Cable Front Raise", muscleGroup: "Shoulders" },
  { id: "straight-bar-dips", name: "Straight Bar Dips", muscleGroup: "Chest" },
  { id: "strict-curl", name: "Strict Curl", muscleGroup: "Biceps" },
  { id: "suitcase-carry", name: "Suitcase Carry", muscleGroup: "Abs" },
  { id: "sumo-deadlift", name: "Sumo Deadlift", muscleGroup: "Back" },
  { id: "sumo-squat", name: "Sumo Squat", muscleGroup: "Glutes" },
  { id: "superman", name: "Superman", muscleGroup: "Back" },
  { id: "supine-spinal-twist", name: "Supine Spinal Twist", muscleGroup: "Back" },
  { id: "supine-windshield-wipers", name: "Supine Windshield Wipers", muscleGroup: "Abs" },
  { id: "supported-shoulderstand", name: "Supported Shoulderstand", muscleGroup: "Abs" },
  { id: "svend-press", name: "Svend Press", muscleGroup: "Chest" },
  { id: "t-bar-row", name: "T-Bar Row", muscleGroup: "Back" },
  { id: "thoracic-bridge", name: "Thoracic Bridge", muscleGroup: "Abs" },
  { id: "thread-the-needle", name: "Thread the Needle", muscleGroup: "Back" },
  { id: "thread-the-needle-flow", name: "Thread the Needle Flow", muscleGroup: "Back" },
  { id: "three-legged-dog", name: "Three-Legged Downward Dog", muscleGroup: "Shoulders" },
  { id: "thruster", name: "Thruster", muscleGroup: "Shoulders" },
  { id: "toes-to-bar", name: "Toes to Bar", muscleGroup: "Abs" },
  { id: "treadmill-running", name: "Treadmill Running", muscleGroup: "Other" },
  { id: "tree-pose", name: "Tree Pose", muscleGroup: "Glutes" },
  { id: "triangle-pose", name: "Triangle Pose", muscleGroup: "Hamstrings" },
  { id: "tricep-kickback", name: "Dumbbell Tricep Kickback", muscleGroup: "Triceps" },
  { id: "tricep-pushdown", name: "Cable Tricep Pushdown", muscleGroup: "Triceps" },
  { id: "trx-bicep-curl", name: "TRX Bicep Curl", muscleGroup: "Biceps" },
  { id: "trx-chest-press", name: "TRX Chest Press", muscleGroup: "Chest" },
  { id: "trx-face-pull", name: "TRX Face Pull", muscleGroup: "Shoulders" },
  { id: "trx-hamstring-curl", name: "TRX Hamstring Curl", muscleGroup: "Hamstrings" },
  { id: "trx-lunge", name: "TRX Lunge", muscleGroup: "Glutes" },
  { id: "trx-pistol-squat", name: "TRX Pistol Squat", muscleGroup: "Glutes" },
  { id: "trx-plank", name: "TRX Plank", muscleGroup: "Abs" },
  { id: "trx-row", name: "TRX Row", muscleGroup: "Back" },
  { id: "trx-side-plank", name: "TRX Side Plank", muscleGroup: "Abs" },
  { id: "trx-squat", name: "TRX Squat", muscleGroup: "Glutes" },
  { id: "trx-tricep-extension", name: "TRX Triceps Extension", muscleGroup: "Triceps" },
  { id: "trx-y-fly", name: "TRX Y-Fly", muscleGroup: "Shoulders" },
  { id: "upright-row", name: "Barbell Upright Row", muscleGroup: "Shoulders" },
  { id: "upward-dog", name: "Upward-Facing Dog", muscleGroup: "Abs" },
  { id: "v-bar-lat-pulldown", name: "V-Bar Lat Pulldown", muscleGroup: "Back" },
  { id: "v-bar-tricep-pushdown", name: "V-Bar Tricep Pushdown", muscleGroup: "Triceps" },
  { id: "v-sit", name: "V-Sit", muscleGroup: "Abs" },
  { id: "v-ups", name: "V Ups", muscleGroup: "Abs" },
  { id: "walking", name: "Walking", muscleGroup: "Other" },
  { id: "walking-lunge", name: "Walking Lunge", muscleGroup: "Glutes" },
  { id: "wall-push-ups", name: "Wall Push Ups", muscleGroup: "Chest" },
  { id: "wall-sit", name: "Wall Sit", muscleGroup: "Glutes" },
  { id: "warrior-one", name: "Warrior I", muscleGroup: "Glutes" },
  { id: "warrior-three", name: "Warrior III", muscleGroup: "Hamstrings" },
  { id: "warrior-two", name: "Warrior II", muscleGroup: "Glutes" },
  { id: "weighted-dips", name: "Weighted Dips", muscleGroup: "Chest" },
  { id: "weighted-pull-up", name: "Weighted Pull-Up", muscleGroup: "Back" },
  { id: "weighted-wall-crunch", name: "Weighted Wall Crunch", muscleGroup: "Abs" },
  { id: "wide-grip-bench-press", name: "Wide-Grip Bench Press", muscleGroup: "Chest" },
  { id: "wide-grip-pull-ups", name: "Wide Grip Pull Ups", muscleGroup: "Back" },
  { id: "wide-grip-push-ups", name: "Wide Grip Push Ups", muscleGroup: "Chest" },
  { id: "wide-grip-seated-cable-row", name: "Wide Grip Seated Cable Row", muscleGroup: "Back" },
  { id: "wide-legged-forward-fold", name: "Wide-Legged Forward Fold", muscleGroup: "Hamstrings" },
  { id: "wide-stance-leg-press", name: "Wide-Stance Leg Press", muscleGroup: "Other" },
  { id: "wrist-curl", name: "Bilateral Dumbbell Wrist Curl", muscleGroup: "Other" },
  { id: "wrist-roller", name: "Wrist Roller", muscleGroup: "Other" },
  { id: "zottman-curl", name: "Zottman Curl", muscleGroup: "Biceps" },
];
