export type ExerciseVisual = {
  image: string;
  alt: string;
};

const rules: Array<[RegExp, string]> = [
  [/incline.*dumbbell.*press/i,"incline-dumbbell-press.webp"],
  [/incline.*bench.*press/i,"incline-bench-press.webp"],
  [/decline.*bench.*press/i,"decline-bench-press.webp"],
  [/close.?grip.*bench/i,"close-grip-bench-press.webp"],
  [/\bbench press\b/i,"bench-press.webp"],
  [/chest press/i,"chest-press-machine.webp"],
  [/pec deck|chest fly.*machine/i,"pec-deck-fly.webp"],
  [/high.?to.?low.*cable|cable.*high.?to.?low/i,"cable-fly-high-to-low.webp"],
  [/low.?to.?high.*cable|cable.*low.?to.?high/i,"cable-fly-low-to-high.webp"],
  [/cable crossover|cable fly/i,"cable-crossover.webp"],
  [/dumbbell fly/i,"dumbbell-fly.webp"],
  [/push.?up/i,"push-up.webp"],
  [/wide.*pull.?up/i,"pull-up.webp"],
  [/pull.?up/i,"pull-up.webp"],
  [/lat pulldown|pulldown/i,"lat-pulldown.webp"],
  [/seated.*row|cable row/i,"seated-row.webp"],
  [/t.?bar row/i,"t-bar-row.webp"],
  [/single.?arm.*dumbbell.*row|one.?arm.*dumbbell.*row/i,"single-arm-dumbbell-row.webp"],
  [/landmine row/i,"landmine-row.webp"],
  [/bent.?over.*row|barbell row/i,"bent-over-row.webp"],
  [/romanian deadlift/i,"romanian-deadlift.webp"],
  [/stiff.?leg.*deadlift/i,"stiff-leg-deadlift.webp"],
  [/trap.?bar.*deadlift/i,"trap-bar-deadlift.webp"],
  [/sumo.*deadlift/i,"sumo-deadlift.webp"],
  [/\bdeadlift\b/i,"deadlift.webp"],
  [/arnold press/i,"arnold-press.webp"],
  [/overhead press|shoulder press/i,"overhead-press.webp"],
  [/cable.*lateral raise/i,"lateral-raise.webp"],
  [/lateral raise/i,"lateral-raise.webp"],
  [/front raise/i,"front-raise.webp"],
  [/rear delt.*machine|reverse fly.*machine/i,"rear-delt-fly-machine.webp"],
  [/face pull/i,"face-pull.webp"],
  [/upright row/i,"upright-row.webp"],
  [/shrug/i,"shrug.webp"],
  [/hammer curl/i,"hammer-curl.webp"],
  [/preacher curl/i,"preacher-curl.webp"],
  [/concentration curl/i,"concentration-curl.webp"],
  [/cable curl/i,"cable-curl.webp"],
  [/biceps.*curl|dumbbell curl|barbell curl/i,"biceps-curl.webp"],
  [/rope.*pushdown|pushdown.*rope/i,"triceps-pushdown-rope.webp"],
  [/triceps.*pushdown|pushdown/i,"triceps-pushdown.webp"],
  [/overhead.*triceps/i,"overhead-triceps-extension.webp"],
  [/triceps.*dip/i,"triceps-dips.webp"],
  [/front squat/i,"front-squat.webp"],
  [/hack squat/i,"hack-squat.webp"],
  [/zercher squat/i,"zercher-squat.webp"],
  [/goblet squat/i,"kettlebell-goblet-squat.webp"],
  [/jump squat/i,"jump-squat.webp"],
  [/\bsquat\b/i,"squat.webp"],
  [/leg press/i,"leg-press.webp"],
  [/bulgarian/i,"bulgarian-split-squat.webp"],
  [/walking lunge/i,"walking-lunge.webp"],
  [/curtsy lunge/i,"curtsy-lunge.webp"],
  [/lateral lunge/i,"cable-lateral-lunge.webp"],
  [/\blunge\b/i,"lunge.webp"],
  [/leg extension/i,"leg-extension.webp"],
  [/lying.*leg curl/i,"lying-leg-curl.webp"],
  [/seated.*leg curl/i,"seated-leg-curl.webp"],
  [/hip thrust/i,"hip-thrust.webp"],
  [/glute bridge/i,"glute-bridge.webp"],
  [/kickback/i,"cable-kickback.webp"],
  [/hip abduction/i,"hip-abduction-machine.webp"],
  [/hip adduction|adductor/i,"hip-adduction-machine.webp"],
  [/standing.*calf|calf raise.*standing/i,"standing-calf-raise.webp"],
  [/seated.*calf/i,"seated-calf-raise.webp"],
  [/donkey.*calf/i,"donkey-calf-raise.webp"],
  [/tibialis/i,"tibialis-raise.webp"],
  [/machine.*crunch|ab crunch/i,"ab-crunch-machine.webp"],
  [/cable crunch/i,"cable-crunch.webp"],
  [/hanging.*leg raise/i,"hanging-leg-raise.webp"],
  [/captain.*chair/i,"captains-chair-leg-raise.webp"],
  [/russian twist/i,"russian-twist.webp"],
  [/side plank/i,"side-plank.webp"],
  [/\bplank\b/i,"plank.webp"],
  [/ab wheel/i,"ab-wheel-rollout.webp"],
  [/back extension/i,"back-extension.webp"],
  [/good morning/i,"good-morning.webp"],
  [/glute ham/i,"glute-ham-raise.webp"],
  [/hip hinge/i,"hip-hinge-dowel.webp"],
  [/farmer/i,"farmers-walk.webp"],
  [/suitcase carry/i,"suitcase-carry.webp"],
  [/\bclean\b/i,"clean.webp"],
  [/snatch/i,"snatch.webp"],
  [/kettlebell swing/i,"kettlebell-swing.webp"],
  [/kettlebell clean/i,"kettlebell-clean.webp"],
  [/landmine press/i,"landmine-press.webp"],
  [/step.?up/i,"step-up.webp"],
  [/box jump/i,"box-jump.webp"],
  [/sled push/i,"sled-push.webp"],
  [/sled pull/i,"sled-pull.webp"],
  [/battle rope.*slam/i,"battle-rope-slam.webp"],
  [/battle rope/i,"battle-rope-wave.webp"],
  [/medicine ball slam/i,"medicine-ball-slam.webp"],
  [/wall ball/i,"wall-ball.webp"],
  [/burpee/i,"burpee.webp"],
  [/mountain climber/i,"mountain-climber.webp"],
  [/bear crawl/i,"bear-crawl.webp"],
  [/plate raise/i,"plate-raise.webp"],
];

export function getExerciseVisual(exerciseName: string): ExerciseVisual | null {
  const found = rules.find(([pattern]) => pattern.test(exerciseName));
  if (!found) return null;
  return {
    image: `/exercises/${found[1]}`,
    alt: `${exerciseName} exercise demonstration`,
  };
}
